### ISSUE TITLE
Spike: Understand Data formats/Integration into Maven and Clinisys

### ISSUE THREAD

**Issue by arinkulshi-skylight** [CDCgov/ReportVision#130]
As part of our pilot program with STLT's we need to understand the challenges that come with putting data into Maven or Clinisys assume our data is in JSON format the question we should answer is
1. What should the output data format look like(single entries vs bulk upload) 
2. Which data transfer protocol is utilized(SFTP,API,Queue)

Notes: 
Thoughts from another engineer (Dan on Dibbs)
I believe you can use MIF files. MIF = Maven Interface Format.
extract data with OCR
transform into MIF
load into Maven by delivering the MIF files
I think this would work and is really just a classic ETL (Extract Transform Load) process.

**Comment by bora-skylight** [comment]
@arinkulshi-skylight let's put this in the ice box for now

**Comment by bora-skylight** [comment]
Won't Do
