### ISSUE TITLE
Request Azure Infra ATO

### ISSUE THREAD

**Issue by zdeveloper** [CDCgov/ReportVision#172]
**Is your feature request related to a problem? Please describe.**
We want to host IDWA MDE on CDC Azure

**Describe the solution you'd like**
We like to secure an ATO and access to the CDC Azure cloud

**Additional context**
Setup a meeting with the access team
Develop needed material to secure access

**Comment by marycrawford** [comment]
@bora-skylight -can this ticket can be closed out?  I think you mentioned this will not be hosted in the CDC Azure environment correct?
