### ISSUE TITLE
[V1] Extract: [loading screen] setup the the processing data page

### ISSUE THREAD

**Issue by zdeveloper** [CDCgov/ReportVision#185]
On this page show the loading screen while the ocr api is processing the file that was uploaded

**Acceptance Criteria**
- upload each page to the ocr api
- follow the attached design, use uswds components without customization
- the route to this page should be `/extract/process`
- the back and submit buttons should be disabled
- once all pages are done processing,
  - save the response to the local storage
  - then route to `/extract/review`
- the x button should route to `/`

**Additional context**
https://www.figma.com/design/1FW8ZSDV90q2wpRPOADE9r/MDE?node-id=108-4721&t=BK8Fi3dzPw4X4ZBl-4

![image](https://github.com/user-attachments/assets/9c1ce8d4-482a-47b2-be94-152faa01dfeb)

**Comment by bora-skylight** [comment]
@zdeveloper drop in instructions on how to call OCR API

**Comment by zdeveloper** [comment]
> @zdeveloper drop in instructions on how to call OCR API

To Run the OCR API
`fastapi dev ocr/api.py` [ref](https://github.com/CDCgov/IDWA/blob/main/OCR/README.md?plain=1#L63-L71)

go to `localhost:8000/docs` for instructions on how to call the `image-to-text` endpoint
