### ISSUE TITLE
[V1] Concept / Usability Testing Research Plan

### ISSUE THREAD

**Issue by bora-skylight** [CDCgov/ReportVision#193]

**Comment by Miringuk** [comment]
[Concept Testing Plan](https://docs.google.com/document/d/1EtACZEiD9JTPNtRzH-AOoxwH8Yzrwa_m9RsKbxZpe3o/edit )

**Comment by zdeveloper** [comment]
Still in review

**Comment by bora-skylight** [comment]
Pending CDC stakeholder review

**Comment by bora-skylight** [comment]
@Miringuk let's separate this from Respondent and finalize it for using with Virginia
