### ISSUE TITLE
Outline different paths & considerations for how our product is hosted

### ISSUE THREAD

**Issue by bora-skylight** [CDCgov/ReportVision#218]
Acceptance Criteria:

- Create a document that outlines all of the hosting options and how they would impact development timeline & implementation at STLTs
- Socialize document and gather feedback from MDE & DIBBs eng
- Present to Rebecca at team meeting on 09/16

**Comment by bora-skylight** [comment]
Hey @zdeveloper @derekadombek can we please put this at the top of your priority list and plan to have something we can at least discuss together by Wednesday EOD?

**Comment by zdeveloper** [comment]
https://docs.google.com/document/d/1vXdeaB9F7NrGsjSbzO9PgMYyLI54j4YlzWDscnPDD3Y/edit
