### ISSUE TITLE
Respondent Screener

### ISSUE THREAD

**Issue by Miringuk** [CDCgov/ReportVision#234]

**Comment by bora-skylight** [comment]
Waiting on approval for charging card for Respondent

**Comment by bora-skylight** [comment]
@Miringuk should this one be closed?

**Comment by bora-skylight** [comment]
Putting in Ice Box since we can't launch the screener until CDC review has been provided

**Comment by bora-skylight** [comment]
Screener created but not launched because we will not move forward with Respondent study
