### ISSUE TITLE
[Benchmarking Framework] Create a standardized form testing dataset

### ISSUE THREAD

**Issue by zdeveloper** [CDCgov/ReportVision#254]
Create a standardized form testing dataset based on a readily available dataset, this will be used for building a standard benchmark for ReportVision

**Acceptance Criteria**
- The dataset should include at least 100 different variations of the same form
- The dataset should include around 10 different forms(ex: quest form,tb form, syph form etc.) 
- The dataset should include the ground truth of the data (label/value) present in each form
- add dataset to the git repo, and whatever code was used to generate it
- name this dataset: `reportvision-dataset-1
`

**Additional context**
Example of datasets came be coming from NIST or huggingface
Please be very communicative and the AC can be adjusted

**Comment by zdeveloper** [comment]
potential datasets: https://huggingface.co/datasets/singhsays/fake-w2-us-tax-form-dataset

**Comment by schreiaj** [comment]
Per discussion - the goal of this is to build a dataset to test the OCR not alignment.
