### ISSUE TITLE
[Benchmarking Framework] Establish e2e benchmarking framework

### ISSUE THREAD

**Issue by zdeveloper** [CDCgov/ReportVision#255]
Establish e2e benchmarking framework by using the created `reportvision-dataset-1`
we want to automate the measurement or accuracy and speed for running that dataset into the ocr pipeline

**Acceptance Criteria**

- write automated tests to measure e2e OCR reportVision accuracy and time to run against the `reportvision-dataset-1`
- also measure the confidence accuracy and at what confidence level are the results not correct
- create the templates manually or using frontend, creating the templates should not be part of the benchmark
- store the benchmark with all required data/scripts on a `benchmark/reportvision-dataset-1` with clear documentation on how to run it.

**Additional context**
- for python example tests, look at OCR model benchmark tests

**Comment by zdeveloper** [comment]
per @schreiaj, please save the segmentation templates so its also standardized for every run

**Comment by arinkulshi-skylight** [comment]
- The steps taken to so far to address this ticket

- [x]  Created segmentation template for datasets, updated output of labels.json file
- [x]  Created and implemented batch segmentation and OCR processing script
- [x]  Added time measurement to OCR processing script
- [ ] - Create batch metrics for OCR pipeline.
