### ISSUE TITLE
Respondent Funding Approval

### ISSUE THREAD

**Issue by Miringuk** [CDCgov/ReportVision#256]

**Comment by Miringuk** [comment]
[Funding Request Doc](https://docs.google.com/document/d/1NuPb3811IiuB7gHVStm8M8Mr8YtV5gGo2sDcSxUekAg/edit)

**Comment by bora-skylight** [comment]
Pending approval from Bruce & approval request from BESPIN & project POCs

**Comment by bora-skylight** [comment]
Currently blocked in STARS review at the CDC

**Comment by bora-skylight** [comment]
We will not be pursuing Respondent because CDC is not comfortable with approving the monetary compensation of participants. Additionally, reviews of Respondent from other Skylight researchers indicate that the quality of Respondent participants will likely be low.
