### ISSUE TITLE
Create Private Networking and DNS for Postgres DB & Server

### ISSUE THREAD

**Issue by bora-skylight** [CDCgov/ReportVision#259]
As a DevOps Engineer, ensure the database is secure by creating a private network and dns for the postgresql db and server.

Accepted Criteria:

[x] Utilize the appropriate subnet for the new postgresql db
[x] Research and apply any and all private dns zones and delegations for the postgresql db

**Comment by marycrawford** [comment]
@bora-skylight apologies for creating a duplicate ticket.  Not sure how to link two tickets together. 
 Do you want me to close out this ticket and just keep the other ticket which can be found [here](https://github.com/orgs/CDCgov/projects/33/views/1?pane=issue&itemId=86980737&issue=CDCgov%7CReportVision%7C389)?

**Comment by bora-skylight** [comment]
@marycrawford Should we just close this one as a Duplicate. Does that sound OK with you?

**Comment by marycrawford** [comment]
Closing this issue out since I created a duplicate ticket [here](https://github.com/orgs/CDCgov/projects/33/views/3?pane=issue&itemId=86980737&issue=CDCgov%7CReportVision%7C389).

**Comment by marycrawford** [comment]
Reopened, and redefined the ticket to focus on creating the private network and dns for the postgresql db.
