### ISSUE TITLE
Add color gradient to menu bar on ReportVision homepage

### ISSUE THREAD

**Issue by prikiser** [CDCgov/ReportVision#286]
Enhancement to the design

**Acceptance Criteria**
Please add gradient
Linear gradient #145092
                           #006CAB
                           #0080A1

![Image](https://github.com/user-attachments/assets/cbea84cb-9b18-46bd-be96-6cdf9ea974ed)

[Figma  
](https://www.figma.com/design/1FW8ZSDV90q2wpRPOADE9r/ReportVision?node-id=635-5091&t=HJ3qfEAAKBpRMvA9-1)

**Additional context**
Please view designs in dev mode for more details

**Comment by bora-skylight** [comment]
@prikiser with the limited time that we have, I'm going to deprioritize this ticket and close it out. 
WON'T DO
