### ISSUE TITLE
Create Meaningful 404 Page

### ISSUE THREAD

**Issue by arinkulshi-skylight** [CDCgov/ReportVision#288]
![Image](https://github.com/user-attachments/assets/37774b2e-480b-4c05-928e-030d8f13ce55)

A.C: 
Generate a better 404 page for page links that are currently not active.

**Comment by prikiser** [comment]
@knguyenrise8 here is the SVG ![Image](https://github.com/user-attachments/assets/dc795f71-99e2-43ca-994b-3d808a6f882d)

**Comment by prikiser** [comment]
[Figma Link](https://www.figma.com/design/1FW8ZSDV90q2wpRPOADE9r/ReportVision?node-id=1231-15181&t=em9iYmkR583IEBlG-1)
