### ISSUE TITLE
Each label on Annotation page should have a distinct color

### ISSUE THREAD

**Issue by arinkulshi-skylight** [CDCgov/ReportVision#291]
The colors on the annotation page are not distinct

**Acceptance Criteria**

- [ ] Ensure the colors generated from the annotation page have enough contrast so they can be distinct 

> Consider the approach of calculating fix intervals to separate each color based on the number of colors needed.   
> `const hue = (index * (360 / totalColors)) % 360;`

**Comment by bora-skylight** [comment]
@knguyenrise8 gonna remove this from the sprint for the time being since we want to focus on the Download functionality to complete our end-to-end experience before working on updates / design chores
