### ISSUE TITLE
Clean up UI for file uploading

### ISSUE THREAD

**Issue by prikiser** [CDCgov/ReportVision#300]
- [x]  Incorrect CTA disabled colors #C9C9C9
- [x] Border color of top bar and stepper should be #F0F0F0
- [x] Height of stepper component should be 80px
- [x] Interaction bug currently can click on submit disabled CTA which takes me to next page

![Image](https://github.com/user-attachments/assets/c8c701ba-df35-4bf6-941b-82de314966c8)

[Figma ](https://www.figma.com/design/1FW8ZSDV90q2wpRPOADE9r/ReportVision?node-id=576-8233&t=M9xhPFZ6w9EeP4ww-1)

**Comment by bora-skylight** [comment]
@prikiser @knguyenrise8 I believe this is already done, correct? and this is no longer a relevant ticket?

**Comment by prikiser** [comment]
@bora-skylight @knguyenrise8 I think the top three checkboxes are done; however, maybe not the disabled color? I believe it was still showing up when you demo'd.

**Comment by knguyenrise8** [comment]
ok i can work on this next sprint
