### ISSUE TITLE
Design chore upload new file enhancement [Annotation flow]

### ISSUE THREAD

**Issue by prikiser** [CDCgov/ReportVision#306]
Enhancement of drag and drop component on annotation flow.

The only difference between this and extract flow is we are limiting one file upload at a time for annotation. Currently, there is no way to bulk annotate. Extract flow will not have that limitation. 

**Current**

![Image](https://github.com/user-attachments/assets/c23d9a31-a20f-4a8a-9447-d32618f13d1f)

**Files**
[Upload ](https://www.figma.com/design/1FW8ZSDV90q2wpRPOADE9r/ReportVision?node-id=576-8233&t=M9xhPFZ6w9EeP4ww-1)

[Uploaded ](https://www.figma.com/design/1FW8ZSDV90q2wpRPOADE9r/ReportVision?node-id=933-8408&t=M9xhPFZ6w9EeP4ww-1)

**Comment by bora-skylight** [comment]
@prikiser I believe this has already been updated. If so, would you mind closing this ticket out?
