### ISSUE TITLE
Take findings from Research Spike #249 (Implement other backend models) and implement one model into OCR pipeline.

### ISSUE THREAD

**Issue by arinkulshi-skylight** [CDCgov/ReportVision#321]
Acceptance Criteria 
- [ ]  Implement at least one backend model(tesseract etc) into existing OCR pipeline
- [ ] Apply research and findings from Spike as part of implementation. Please update ticket with subtasks when the spike is complete. (https://github.com/CDCgov/ReportVision/issues/249)

**Comment by bora-skylight** [comment]
Won't Do
