### ISSUE TITLE
Design Chore "Loading" is not a descriptive message, communicate to the user what we’re doing during extraction

### ISSUE THREAD

**Issue by arinkulshi-skylight** [CDCgov/ReportVision#329]
"Loading" is not a descriptive message, communicate to the user what we’re doing during extraction

A.C 
Change the loading message to a message that better defines the work being done
 “Looking document over”, “Extracting Data”, “Bundling it up for you” (Design chore)

**Comment by prikiser** [comment]
@arinkulshi-skylight  there are already designs for that 
[Figma file](https://www.figma.com/design/1FW8ZSDV90q2wpRPOADE9r/ReportVision?node-id=1327-28623&t=6ZHJcRVzM9StAkwY-1)

**Comment by arinkulshi-skylight** [comment]
Awesome I will close it then.
