### ISSUE TITLE
Design Chore Upload Files Extract Flow

### ISSUE THREAD

**Issue by prikiser** [CDCgov/ReportVision#340]
Enhancement + bug
- [ ] Upload with new component
- [ ] Users upload and then select templates 
- [ ] Select template is in same component as upload complete (see designs)

**Current** Is incorrect as it has both template selection and upload in same page![Image](https://github.com/user-attachments/assets/b3276283-938c-4dc8-8eae-9662cdc771b6)

**Design**
![Image](https://github.com/user-attachments/assets/e28d56c6-a534-4367-89ba-fb378441cc75)

[Figma file upload blank
](https://www.figma.com/design/1FW8ZSDV90q2wpRPOADE9r/ReportVision?node-id=1327-31719&t=utYyfPZPlxlytKEg-1)

[Figma file upload completed
](https://www.figma.com/design/1FW8ZSDV90q2wpRPOADE9r/ReportVision?node-id=1327-32019&t=utYyfPZPlxlytKEg-1)

[Figma file template selection
](https://www.figma.com/design/1FW8ZSDV90q2wpRPOADE9r/ReportVision?node-id=1327-31775&t=utYyfPZPlxlytKEg-1)

**Comment by bora-skylight** [comment]
@prikiser I believe this is complete. If you are satisfied with it, let's close this ticket.
