### ISSUE TITLE
Design Chore Annotate Segment Box

### ISSUE THREAD

**Issue by prikiser** [CDCgov/ReportVision#341]
- [ ] Bounding box is opaque which prevents users from seeing the text underneath the segments 

**Current** 
![Image](https://github.com/user-attachments/assets/268c33c4-af00-47e7-a307-49060ced8476)

**Design**![Image](https://github.com/user-attachments/assets/2dc83304-a4a4-4ad1-9f33-b051ca53ee7a)

**Comment by bora-skylight** [comment]
Bounding boxes have been updated to be opaque since this ticket was created. Current state:
![Image](https://github.com/user-attachments/assets/038b6fd3-8821-4d8c-95d6-86fd70beafbe)
