### ISSUE TITLE
Placeholder(Base 64 error)

### ISSUE THREAD

**Issue by arinkulshi-skylight** [CDCgov/ReportVision#381]
Issue with processing base64 value. 
Unknown

Client-side
Backend 

When error is being surfaced

A.C

Address error

**Comment by bora-skylight** [comment]
@arinkulshi-skylight is this ticket still relevant?

**Comment by arinkulshi-skylight** [comment]
If the bug is resolved then I can close it.

**Comment by bora-skylight** [comment]
@arinkulshi-skylight to clarify, I personally don't know how to check this error. If this is still relevant, can you please update the title of this ticket and provide some additional explanation of what this error is and what it prevents. 

The ticket as is is not very helpful, and I don't know how to prioritize it.

**Comment by arinkulshi-skylight** [comment]
I think we are good to close it.
