### ISSUE TITLE
Set up H2(in-memory DB) to be used to store templates in cloud env

### ISSUE THREAD

**Issue by arinkulshi-skylight** [CDCgov/ReportVision#388]
This is a optional ticket if we do not have a azure DB.
To address current security concerns with connecting a persistent database to the Spring Boot API, configure an in-memory database to be used temporarily. Ensure to set up such that Azure DB can replace in-mem DB at a future point in time. 

- [ ] Set up in-memory db H2 in Springboot
- [ ] ensure DB initializes with proper schema
- [ ] ensure the db aligns with the lifecycle of each user
- [ ] test the e2e db lifecycle.

**Comment by bora-skylight** [comment]
@arinkulshi-skylight @schreiaj I believe this is no longer relevant. Can you please confirm that I can close this ticket?

**Comment by arinkulshi-skylight** [comment]
Yes we can close this.
