### ISSUE TITLE
[Design] Create log in designs

### ISSUE THREAD

**Issue by prikiser** [CDCgov/ReportVision#392]
Create designs for simple log in

Data points needed 

- [x] email
- [x] password

[Figma design link
](https://www.figma.com/design/1FW8ZSDV90q2wpRPOADE9r/ReportVision?node-id=1645-12445&t=IHv1V25iFy2FDxXT-1)

![Image](https://github.com/user-attachments/assets/3ca6d0ef-1120-4bce-8dc9-f293e26cbb8c)

**Comment by prikiser** [comment]
@bora-skylight what data fields would be needed for the design?

**Comment by prikiser** [comment]
@bora-skylight @knguyenrise8 created a simple login, let me know if we need to add any other fields.

**Comment by bora-skylight** [comment]
Thank you @prikiser! I don't think we need anything more.
