### ISSUE TITLE
[Design Enhancement] Initial state

### ISSUE THREAD

**Issue by prikiser** [CDCgov/ReportVision#395]
Initial state [blank]
- [ ] Replace existing design with this when users log on for the first time and have not created a template

[Figma design link](https://www.figma.com/design/1FW8ZSDV90q2wpRPOADE9r/ReportVision?node-id=1637-12542&t=PbjaFODxjtEF7FtR-1)

![Image](https://github.com/user-attachments/assets/a83a04ff-5a70-479e-a969-d1ba84bdfcaf)

**Comment by bora-skylight** [comment]
Duplicate of #421
