### ISSUE TITLE
[Design enhancement] Page selector

### ISSUE THREAD

**Issue by prikiser** [CDCgov/ReportVision#398]
**Page selector task bar**

Allows users to view and change pages. 
This variant was originally for the extraction page, but due to time, it should be on both flows.

- [x] Show users numbers of pages and allow them to change in box or use arrows 
- [x] If only one page just show 1 out of 1 and disable interactions

- [ ] zoom in and out functionality of page (it seems we already have the zoom in/out functionality can we also tie it to these icons if its not a big lift?

[Figma designs 
](https://www.figma.com/design/1FW8ZSDV90q2wpRPOADE9r/ReportVision?node-id=1674-4024&t=la9zEsBYkbhB3DoS-1)

![Image](https://github.com/user-attachments/assets/bcdb1108-0a48-47a6-842c-3271a5c27f23)

**Comment by prikiser** [comment]
@knguyenrise8 here's to the toolbar page selector tick!

**Comment by bora-skylight** [comment]
@prikiser page display is complete. Zoom functionality will not be completed by end of project. I think we can close this ticket and create an upcoming features file in Figma instead. how does that sound?

**Comment by bora-skylight** [comment]
Partially implemented. Page selector implemented. Zoom functionality not implemented.
