### ISSUE TITLE
[Design] Standardize error msg

### ISSUE THREAD

**Issue by prikiser** [CDCgov/ReportVision#407]
Standard error messaging to start off with

- [x] choose one style of error message where the user needs to take action

This will be our standard message error, let's deprioritize modal errors for now.
[ Figma design for download error](https://www.figma.com/design/1FW8ZSDV90q2wpRPOADE9r/ReportVision?node-id=1348-14033&t=y4PmhQG4Nla7Hipu-1) which mimics template error

**Comment by prikiser** [comment]
@bora-skylight done with standard error message!

**Comment by bora-skylight** [comment]
Cool! So we can turn this into an eng ticket then @knguyenrise8.

@prikiser quick question, what is the error message supposed to look like if the page the error is on is not the review page, i.e. there is no table, should it just extend the full width of the page?

**Comment by prikiser** [comment]
@bora-skylight correct! There is an earlier error message that @knguyenrise8 did for the template mismatch. The design is the same it just extends to the full width like [this](https://www.figma.com/design/1FW8ZSDV90q2wpRPOADE9r/ReportVision?node-id=1637-12111&t=VStmdfXc0PwJfYKX-1)
