### ISSUE TITLE
[🐞] Eliminate "Submit" CTA on top right across all pages of Data Extraction Workflow

### ISSUE THREAD

**Issue by bora-skylight** [CDCgov/ReportVision#436]
Throughout the ReportVision workflows, we are displaying 2 sets of CTAs to the user, one on the top right corner and another at the bottom left. 

**Acceptance Criteria**
Remove SUBMIT button on the top right corner on the following pages:
- [x] /new-template/upload
- [x] /extract/upload

**Comment by bora-skylight** [comment]
@prikiser Can you please review this bug to confirm what the intended design is supposed to be and add more detailed instructions for @knguyenrise8?

**Comment by prikiser** [comment]
@bora-skylight, correct. The submit CTA should no longer be in the extraction flow. It was removed a while back when we moved away from Report Strean.

@knguyenrise8, could you remove the submit CTA from the top on all pages? The back button should still allow users to return to the previous step.

[Figma file
](https://www.figma.com/design/1FW8ZSDV90q2wpRPOADE9r/ReportVision?node-id=1630-10913&t=zRXalooMJL5SBNxg-1)![Upload new form](https://github.com/user-attachments/assets/84830e2a-a368-4d15-a7a4-aca5e57c3ab4)

**Comment by bora-skylight** [comment]
@prikiser can you take a look at the Review page where both `Download CSV` and `Done` are currently displayed as the primary CTA with equal priority.

**Comment by bora-skylight** [comment]
@knguyenrise8 @prikiser FYI: updated the Acceptance Criteria for this ticket to:

**Acceptance Criteria**
Remove SUBMIT button on the top right corner on the following pages:
- [ ] /new-template/upload
- [ ] /extract/upload
